CREATE TABLE CLIENTES(
	ID_CLI INT IDENTITY NOT NULL,
	NOME NVARCHAR(80) NOT NULL,
	CIDADE NVARCHAR(40) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	TELEFONE NVARCHAR(9) NOT NULL,
	EMAIL NVARCHAR(80) NULL,
	CONSTRAINT ID_CLI_PRIMARY PRIMARY KEY(ID_CLI))
)